# Generated by Django 2.2.2 on 2019-06-12 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='assignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sampleapp.Todo')),
            ],
        ),
    ]
